plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation "net.caffeinemc:sodium-fabric:${sodium_version}"
    implementation "net.caffeinemc:sodium-fabric-api:${sodium_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
//    mixin {
//        defaultRefmapName.set("${mod_id}.refmap.json")
//    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
    }
}