pluginManagement {
    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    name = "Fabric"
                    url = "https://maven.fabricmc.net"
                }
            }
            filter {
                includeGroupAndSubgroups("net.fabricmc")
                includeGroup("net.fabricmc.fabric-loom-remap")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "NeoForge"
                    url = "https://maven.neoforged.net/releases"
                }
            }
            filter {
                includeGroupAndSubgroups("net.neoforged")
                includeGroup("codechicken")
            }
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

// This should match the folder name of the project, or else IDEA may complain (see https://youtrack.jetbrains.com/issue/IDEA-317606)
rootProject.name = 'sodium-shadowy-path-blocks'
include('common')
include('fabric')
include('neoforge')