plugins {
    id 'multiloader-common'
    id 'net.fabricmc.fabric-loom-remap'
}

loom {
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
//    mixin {
//        defaultRefmapName.set("${mod_id}.refmap.json")
//    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }

    compileOnly "net.fabricmc:sponge-mixin:${mixin_version}"
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"
    annotationProcessor "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"

    compileOnly "maven.modrinth:sodium:mc1.21.1-0.6.13-neoforge"

    modCompileOnly "net.caffeinemc:sodium-fabric:${sodium_version}"
    modCompileOnly "net.caffeinemc:sodium-fabric-api:${sodium_version}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}